Validations
enis-memic/blog-app pull request #3
Opened 2023-06-07 12:56 UTC by enis-memic

## In this PR I did the following:

### Add the following validations:

-  For the User model:
      Name must not be blank.
      PostsCounter must be an integer greater than or 
      equal to zero.

-  For the Post model:
     Title must not be blank.
     Title must not exceed 250 characters.
     CommentsCounter must be an integer greater 
     than or equal to zero.
     LikesCounter must be an integer greater than or 
     equal to zero.

- Add unit specs for all of your models' methods and validations.

2023-06-07 14:09 UTC, OyePriscilla requested changes
Hi @enis-memic 👍, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Implemented validations for models ✔️ 
Write unit tests for some of the models' methods ✔️ 

## Required Changes ♻️

- [ ] @enis-memic **Please kindly fix your license link (README file); I got 404 error at the moment. 👍  Fixing it will make your README looks professional.** ℹ️ 

- [ ] Kindly ensure to implement unit test for all the methods in post and user model accordingly. **You did well implementing unit test for the methods in comment and likes models.** 👍 👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 14:09 UTC, OyePriscilla commented on app/models/user.rb
>    end
- [ ] Please kindly implement unit test for this method as well according to the project requirement. 👍

2023-06-07 14:09 UTC, OyePriscilla commented on app/models/post.rb
>  end
- [ ] Please kindly implement unit test for all the methods in post model as well according to the project requirement. 👍

2023-06-08 09:04 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @enis-memic 

Your project is complete! Great job for implementing the previous reviewers changes 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Validations correctly implemented
- Test well added
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

![kd](https://media.giphy.com/media/d0NnEG1WnnXqg/giphy.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 09:05 UTC, merged